package com.barbosa.dscommerse.repositories;

import com.barbosa.dscommerse.entities.Category;
import com.barbosa.dscommerse.factories.Factory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
class CategoryRepositoryTest {

    @Autowired
    private CategoryRepository categoryRepository;

    private Long existingId;
    private Long nonExistingId;

    @BeforeEach
    void setUp() {
        existingId = 1L;
        nonExistingId = 9999L;
    }

    @Test
    void findAllShouldReturnNonEmptyList() {
        List<Category> result = categoryRepository.findAll();
        assertNotNull(result);
        assertFalse(result.isEmpty());
    }

    @Test
    void findByIdShouldReturnCategoryWhenIdExists() {
        Optional<Category> result = categoryRepository.findById(existingId);
        assertTrue(result.isPresent());
        assertEquals(existingId, result.get().getId());
        assertNotNull(result.get().getName());
    }

    @Test
    void findByIdShouldReturnEmptyWhenIdDoesNotExist() {
        Optional<Category> result = categoryRepository.findById(nonExistingId);
        assertTrue(result.isEmpty());
    }

    @Test
    void saveShouldPersistCategoryWithAutoGeneratedId() {
        Category category = Factory.createCategory(null, "Nova Categoria");

        category = categoryRepository.save(category);

        assertNotNull(category.getId());
        assertEquals("Nova Categoria", category.getName());
    }
}
