package com.barbosa.dscommerse.repositories;

import com.barbosa.dscommerse.entities.Category;
import com.barbosa.dscommerse.entities.Product;
import com.barbosa.dscommerse.factories.Factory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.ActiveProfiles;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
class ProductRepositoryTest {

    @Autowired
    private ProductsRepository productsRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    private Long existingId;
    private Long nonExistingId;

    @BeforeEach
    void setUp() {
        existingId = 1L;
        nonExistingId = 9999L;
    }

    @Test
    void saveShouldPersistProductWithAutoGeneratedId() {
        Product product = Factory.createProduct();
        product.setId(null);
        Category cat = categoryRepository.save(Factory.createCategory(null, "Eletrônicos"));
        product.getCategories().clear();
        product.getCategories().add(cat);

        product = productsRepository.save(product);

        assertNotNull(product.getId());
        assertTrue(product.getId() > 0);
    }

    @Test
    void findByIdShouldReturnProductWhenIdExists() {
        Product product = Factory.createProduct();
        product.setId(null);
        Category cat = categoryRepository.save(Factory.createCategory(null, "Eletrônicos"));
        product.getCategories().clear();
        product.getCategories().add(cat);
        product = productsRepository.save(product);

        Optional<Product> result = productsRepository.findById(product.getId());

        assertTrue(result.isPresent());
        assertEquals(product.getId(), result.get().getId());
        assertEquals("Phone", result.get().getName());
    }

    @Test
    void findByIdShouldReturnEmptyWhenIdDoesNotExist() {
        Optional<Product> result = productsRepository.findById(nonExistingId);
        assertTrue(result.isEmpty());
    }

    @Test
    void searchByNameShouldReturnPageOfProductsWhenNameMatches() {
        Page<Product> result = productsRepository.searchByName("Lord", PageRequest.of(0, 10));
        assertFalse(result.isEmpty());
        assertTrue(result.getContent().stream()
                .anyMatch(p -> p.getName().contains("Lord")));
    }

    @Test
    void searchByNameShouldReturnEmptyPageWhenNameDoesNotMatch() {
        Page<Product> result = productsRepository.searchByName("XyzNonexistent", PageRequest.of(0, 10));
        assertTrue(result.isEmpty());
    }

    @Test
    void searchByNameWithEmptyStringShouldReturnAllProducts() {
        Page<Product> result = productsRepository.searchByName("", PageRequest.of(0, 25));
        assertFalse(result.isEmpty());
    }

    @Test
    void deleteShouldRemoveProductWhenIdExists() {
        Product product = Factory.createProduct();
        product.setId(null);
        Category cat = categoryRepository.save(Factory.createCategory(null, "Eletrônicos"));
        product.getCategories().clear();
        product.getCategories().add(cat);
        product = productsRepository.save(product);
        Long id = product.getId();

        productsRepository.deleteById(id);

        Optional<Product> result = productsRepository.findById(id);
        assertTrue(result.isEmpty());
    }

    @Test
    void existsByIdShouldReturnTrueWhenIdExists() {
        assertTrue(productsRepository.existsById(existingId));
    }

    @Test
    void existsByIdShouldReturnFalseWhenIdDoesNotExist() {
        assertFalse(productsRepository.existsById(nonExistingId));
    }
}
